include: package:flutter_lints/flutter.yaml

analyzer:
  #errors:
    #deprecated_member_use: ignore
    #avoid_print: ignore
    #deprecated_member_use_from_same_package: ignore
    #unused_catch_stack: ignore
    #unrelated_type_equality_checks: ignore
    #use_build_context_synchronously: ignore

linter:
  rules:
    # Performance Improvements
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_redundant_argument_values: true
    prefer_final_locals: true

    # Important Warnigns & Best Practices
    avoid_dynamic_calls: true
    prefer_const_declarations: true
    always_declare_return_types: true