name: test_app
description: "Test App."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # APP Splash Screen
  flutter_native_splash: ^2.4.6

  # APP Responsiveness Test METHOD
  device_preview: ^1.2.0

  # APP Custom UI
  flutter_otp_text_field: ^1.5.1+1

  # APP Controller
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  
  # APP Responsiveness
  flutter_screenutil: ^5.9.3

  # APP ICONs, IMGs
  flutter_svg: ^2.0.17

  # APP NAVIGATION
  go_router: ^14.8.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0

  flutter_test:
    sdk: flutter

  # Riverpod
  riverpod_generator: ^2.6.4
  riverpod_lint: any

flutter:
  uses-material-design: true

  # APP FONTS
  fonts:
    # ROBOTO
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 800
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
    # SomarSans
    - family: Somar
      fonts:
        - asset: assets/fonts/somar/SomarSans-Bold.ttf
          weight: 800
        - asset: assets/fonts/somar/SomarSans-Regular.ttf
    # Cairo
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 800
        - asset: assets/fonts/cairo/Cairo-Regular.ttf

  # APP ASSETS
  assets:
    - assets/icons/Splash/
    - assets/icons/AppForm/
    - assets/icons/AppIcon/
    - assets/icons/AppHeader/
    - assets/icons/Login/
    - assets/icons/ForgetPassword/
    - assets/icons/RestPassword/
    - assets/icons/Verification/
    - assets/icons/Countries/
    - assets/images/

# APP Splash Screen
flutter_native_splash:
  # Customize the parameters below, and run the following command in the terminal: dart run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal: dart run flutter_native_splash:remove
  image: "assets/icons/AppIcon/App_Icon_200.png"
  color: "#003082"
  #background_image: "assets/icons/AppIcon/App_Icon.png"
  #branding: "assets/dart.png"
  #branding_mode: bottom
  #branding_bottom_padding: 24
  #image_dark: "assets/splash-invert.png"
  #background_image_dark: "assets/dark-background.png"
  #color_dark: "#042a49"
  #branding_dark: "assets/dart_dark.png"
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

  android_12:
    image: "assets/icons/AppIcon/App_Icon_200.png"
    color: "#003082"
    #icon_background_color: "#111111"
    #branding: "assets/icons/AppIcon/App_Icon.png"
    #image_dark: "assets/android12splash-invert.png"
    #icon_background_color_dark: "#eeeeee"
    #color_dark: "#042a49"
    fullscreen: true

  android: true
  ios: true
