name: test_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  # APP UI on Other Devices
  device_preview: ^1.2.0

  flutter:
    sdk: flutter

  # APP Responsive UI
  flutter_screenutil: ^5.9.3

  # APP SVG ICONS
  flutter_svg: ^2.0.17

  # APP Navigation
  go_router: ^14.8.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  # APP FONTS
  fonts:

  # ROBOTO
  - family: Roboto
    fonts:
      - asset: assets/fonts/roboto/Roboto-Bold.ttf
        weight: 800
      - asset: assets/fonts/roboto/Roboto-Regular.ttf


  #SomarSans
      - asset: assets/fonts/somar/SomarSans-Bold.ttf
        weight: 800
      - asset: assets/fonts/somar/SomarSans-Regular.ttf


  # APP ASSETS
  assets:
    - assets/icons/Splash/
    - assets/icons/AppForm/
    - assets/icons/Login/
    - assets/images/